[package]
name        = "nps-nwp"
description = "NPS — Neural Web Protocol frames (QueryFrame, ActionFrame) and async HTTP client."
version.workspace     = true
edition.workspace     = true
license.workspace     = true
authors.workspace     = true
repository.workspace  = true
homepage.workspace    = true

[dependencies]
nps-core     = { workspace = true }
nps-ncp      = { workspace = true }
nps-nip      = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
time         = { workspace = true }
tokio        = { workspace = true }
reqwest      = { workspace = true, features = ["stream"] }
futures      = { workspace = true }
thiserror    = { workspace = true }
async-stream = { workspace = true }
bytes        = { workspace = true }

[dev-dependencies]
tiny_http = { workspace = true }
tokio     = { workspace = true }
